/*
  Warnings:

  - The values [WORKSHOP,COMPETITION,SEMINAR,SPORTS,CAREER,ACADEMIC,SOCIAL,PROFESSIONAL,INDUSTRY_VISIT,JOB_FAIR,CAREER_WORKSHOP,INTERVIEW_PREPARATION,NETWORKING_EVENT,PROFESSIONAL_DEVELOPMENT,INTERNSHIP_PROGRAM,GUEST_LECTURE] on the enum `Category` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Category_new" AS ENUM ('CULTURAL', 'CONCERTS', 'MUSICAL', 'THEATRE_DRAMA', 'DANCE_PERFORMANCES', 'ART_EXHIBITIONS', 'FILM_SCREENINGS', 'COMEDY_SHOWS', 'FESTIVALS', 'CHARITY_DEDICATION', 'DONATION_DRIVES', 'COMMUNITY_GATHERINGS', 'CULTURAL_FAIRS', 'OPEN_MIC_NIGHTS', 'TALENT_SHOWS', 'BOOK_READINGS', 'FOOD_FESTIVALS', 'FASHION_SHOWS', 'FUNDRAISING_EVENTS', 'WORKSHOPS_CREATIVE', 'SPORTS_EVENTS');
ALTER TABLE "Event" ALTER COLUMN "category" TYPE "Category_new" USING ("category"::text::"Category_new");
ALTER TYPE "Category" RENAME TO "Category_old";
ALTER TYPE "Category_new" RENAME TO "Category";
DROP TYPE "Category_old";
COMMIT;

-- AlterTable
ALTER TABLE "Photo" ADD COLUMN     "clubId" INTEGER;

-- AddForeignKey
ALTER TABLE "Photo" ADD CONSTRAINT "Photo_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Club"("id") ON DELETE SET NULL ON UPDATE CASCADE;
